### ISSUE TITLE
WebEX Teams Space Link Not Working

### ISSUE THREAD

**Issue by JaredF** [CiscoDevNet/cml-community#42]
The WebEX Teams Space link doesn't seem to be working:  https://eurl.io/#bWHTbWz1Z

**Comment by tombry** [comment]
That link shows up here: https://github.com/CiscoDevNet/cml-community#getting-help  

It's part of Hank's first commit for this repository.  I'm not sure what the intent was.  We do not have a WebEx space for general purpose CML support.

Since it shows up right under the section about trying CML in the DevNet Sandbox, I guess that link is supposed to open the **Cisco Modeling Labs (CML) Sandbox Support space**.  But I'm not sure whether it's really appropriate to post that link in the cml-community repository's README.  That WebEx space is specifically for help using CML in the DevNet Sandbox, and we do not want CML users trying to ask support questions there.  

I propose that we fix it by removing that line.  We could maybe add some additional links, such as 

- [CML Documentation](https://developer.cisco.com/docs/modeling-labs/)
- [Introduction to Network Simulations with Cisco Modeling Labs - Free training on Cisco U](https://u.cisco.com/paths/243)
- [CML Videos and Webinar Recordings](https://learningnetwork.cisco.com/s/cml-training-videos)

**Comment by xorrkaz** [comment]
@tombry Can you either commit your desired changes or offer a PR?
